// constants.js

// User actions
export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAILURE = "REGISTER_USER_FAILURE";

export const FETCH_ALL_USERS_REQUEST = "FETCH_ALL_USERS_REQUEST";
export const FETCH_ALL_USERS_SUCCESS = "FETCH_ALL_USERS_SUCCESS";
export const FETCH_ALL_USERS_FAILURE = "FETCH_ALL_USERS_FAILURE";

export const LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILURE = "LOGIN_USER_FAILURE";

// Chat actions
export const CREATE_NEW_CHAT_REQUEST = "CREATE_NEW_CHAT_REQUEST";
export const CREATE_NEW_CHAT_SUCCESS = "CREATE_NEW_CHAT_SUCCESS";
export const CREATE_NEW_CHAT_FAILURE = "CREATE_NEW_CHAT_FAILURE";

export const FETCH_CHATS_REQUEST = "FETCH_CHATS_REQUEST";
export const FETCH_CHATS_SUCCESS = "FETCH_CHATS_SUCCESS";
export const FETCH_CHATS_FAILURE = "FETCH_CHATS_FAILURE";

export const UPDATE_CHAT = "UPDATE_CHAT";

// Message actions

export const ADD_MESSAGE_REQUEST = "ADD_MESSAGE_REQUEST";
export const ADD_MESSAGE_SUCCESS = "ADD_MESSAGE_SUCCESS";
export const ADD_MESSAGE_FAILURE = "ADD_MESSAGE_FAILURE";

export const FETCH_MESSAGES_REQUEST = "FETCH_MESSAGES_REQUEST";
export const FETCH_MESSAGES_SUCCESS = "FETCH_MESSAGES_SUCCESS";
export const FETCH_MESSAGES_FAILURE = "FETCH_MESSAGES_FAILURE";

export const FETCH_USER_MESSAGES_REQUEST = "FETCH_USER_MESSAGES_REQUEST";
export const FETCH_USER_MESSAGES_SUCCESS = "FETCH_USER_MESSAGES_SUCCESS";
export const FETCH_USER_MESSAGES_FAILURE = "FETCH_USER_MESSAGES_FAILURE";
